# Generated by Django 4.0.6 on 2022-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
