# Generated by Django 4.0.6 on 2022-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default=1, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
